# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn build:gh-pages && yarn scully
    - run: yarn lint
    - run: yarn test --no-watch --no-progress --browsers=ChromeHeadlessCI
    - run: yarn e2e --protractor-config=e2e/protractor-ci.conf.js
    - uses: crazy-max/ghaction-github-pages@v2.1.0
      if: ${{ github.event_name == 'push' }}
      with:
        build_dir: ./dist/static
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
