# This is a basic workflow that is manually triggered

name: Deploy to GitHub Page

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: crazy-max/ghaction-github-pages@v2.1.0
        with:
          build_dr: ./dist/json-to-protobuf
          jekyll: false

        
